name: Generate Keystore (One-Time Use)

# This allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  generate_key:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 2. Generate Secure Passwords
        id: passwords
        run: |
          KEY_PASS=$(openssl rand -base64 16)
          STORE_PASS=$(openssl rand -base64 16)
          echo "key_password=${KEY_PASS}" >> $GITHUB_OUTPUT
          echo "store_password=${STORE_PASS}" >> $GITHUB_OUTPUT
          
      - name: 3. Generate Keystore File
        run: |
          keytool -genkeypair -v \
            -keystore my-release-key.keystore \
            -alias my-key-alias \
            -keypass "${{ steps.passwords.outputs.key_password }}" \
            -storepass "${{ steps.passwords.outputs.store_password }}" \
            -dname "CN=Your Name, OU=Your Unit, O=Your Org, L=Your City, ST=Your State, C=US" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: 4. Encode Keystore to Base64 and Print Credentials
        run: |
          # Encode the file
          KEYSTORE_BASE64=$(base64 -w 0 my-release-key.keystore)

          # Print everything needed for GitHub Secrets
          echo ""
          echo "=================================================================="
          echo "✅ Keystore Generated! Copy the values below into your GitHub Secrets."
          echo "=================================================================="
          echo ""
          echo "Secret Name: RELEASE_KEYSTORE_PASSWORD"
          echo "Secret Value (COPY THIS):"
          echo "${{ steps.passwords.outputs.store_password }}"
          echo ""
          echo "------------------------------------------------------------------"
          echo ""
          echo "Secret Name: RELEASE_KEY_ALIAS"
          echo "Secret Value (COPY THIS):"
          echo "my-key-alias"
          echo ""
          echo "------------------------------------------------------------------"
          echo ""
          echo "Secret Name: RELEASE_KEY_PASSWORD"
          echo "Secret Value (COPY THIS):"
          echo "${{ steps.passwords.outputs.key_password }}"
          echo ""
          echo "------------------------------------------------------------------"
          echo ""
          echo "Secret Name: RELEASE_KEYSTORE_BASE64"
          echo "Secret Value (COPY THE ENTIRE BLOCK BELOW):"
          echo $KEYSTORE_BASE64
          echo ""
          echo "=================================================================="
          echo "!! REMINDER: After saving these secrets, DELETE this workflow file ('generate-keystore.yml') !! "
          echo "=================================================================="
